triggers:
- envs: []
  last_enabled_at: 2024-03-28 01:10:45.192392
  name: dauntless charm
  pipeline_uuid: colossal_lake
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-24 16:57:00
  status: active
  variables: {}
