name: Create Daily

on:
  workflow_dispatch:
    inputs:
      EXECUTION_DATE:
        description: 'processing date'
        required: false
        type: string

  # schedule:
  #   - cron: "50 23 * * *"

defaults:
  run:
    shell: bash

jobs:
  on_schedule:
    name: Scheduled Run

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        id: checkout-source


      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'


      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt


      - name: Echo
        run: |
          echo "EXECUTION_DATE is ${{ inputs.EXECUTION_DATE }}"
          echo "EXECUTION_DATE=${{ inputs.EXECUTION_DATE }}" >> "$GITHUB_ENV"


      - name: Create Daily data
        env:
          SECRETS_VARS: ${{ secrets.GOOGLE_CREDENTIALS }}
          EXECUTION_DATE: ${{ inputs.EXECUTION_DATE }}
        run: |
          echo "$SECRETS_VARS" > google_credential.json
          python src/transform.py


      - name: Clean up
        if: always()
        run: |
          rm -f google_credential.json || true


